# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "nirae/42_darkly"
 
  config.vm.provider "virtualbox" do |v|
    iso_file = File.join(File.dirname(__FILE__), "Darkly_i386.iso")
    v.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--type", "dvddrive", "--medium", iso_file]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.communicator = ""

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
end
